const shayariList = [
    "Chand se chehra tera,\nDil ki dhadkan mera,\nTere bina adhoora,\nTu hai khushiyon ka zariya.",

    "Dil se jo baatein,\nBina shabdon ke saath,\nTere khayalon mein kho jaate,\nHar lamha teri yaad.",

    "Phoolon ki khushboo,\nTeri yaadon ka rang,\nZindagi mein tu hai,\nMeri pyaar ki dhun.",

    "Dosti ki dori,\nBadhte rahe hum saath,\nHar dard ko bhulaaye,\nMuskurahat se kare baat.",

    "Tere saath ki khushboo,\nTere bina sab suna,\nZindagi ka rang hai,\nTu hai mera jahan.",

    "Raat ki chaadar,\nSitare hai saath,\nTeri yaadon se bhari,\nZindagi ki har baat.",

    "Har khushi ka raaz,\nTera saath hai khaas,\nZindagi ka safar hai,\nTu hai mera aasmaan.",

    "Tere bina sab suna,\nTere saath hai khushi,\nDil ki har baat hai,\nTere liye hai zindagi.",

    "Zindagi ki raahon mein,\nMile jo tu saath,\nHar lamha hai khushiyon ka,\nHai tere pyaar ki baat.",

    "Tere bina adhura sa,\nMera yeh pyaar ka safar,\nTujhse hi hai khushi,\nHar din mera hai teri yaad.",

    "Dil se dil tak,\nPyaar ka rishta hai,\nTujhse hi hai khushi,\nHar pal tu saath hai.",

    "Tere muskurahat ki khushboo,\nJaise phoolon ki khushboo,\nHar lamha tere saath ho,\nMeri zindagi mein tu.",

    "Chandni raaton ka jahan,\nTere pyaar ka armaan,\nTere bina sab suna,\nTu hai mera asmaan.",

    "Zindagi ki khushboo,\nTere saath ka jadoo,\nHar khushi teri yaadon mein,\nTu hai mera haseen sukoon.",

    "Raat ki khamoshi,\nTere pyaar ki baatein,\nDil ki gehraiyon mein,\nHai sirf teri yaad.",

    "Tere pyaar ka nasha,\nHar pal mein hai jashn,\nZindagi ka hai rang,\nTu hai mera armaan.",

    "Phoolon ki tarah khilte,\nPyar ke rang mein chhilte,\nTere saath zindagi guzre,\nHar pal mein tu saath mile.",

    "Mausam hai suhana,\nTera saath hai pyara,\nZindagi mein tu hai,\nHar khushi ka sahara.",

    "Dil ki baatein teri,\nKhushbu se bhari raat,\nTujhse hi hai khushi,\nMeri zindagi ka saath.",

    "Rang birangi khushiyan,\nTere saath hain khushiyan,\nHar din mein teri yaad,\nDil se hoon teri daastaan.",

    "Suno toh saath mein,\nKhushiyon ki baatein hum,\nDosti ka rishta hai,\nHar pal hai suhana gum.",

    "Dil ki hai gehraai,\nTere pyaar ki baatein,\nZindagi ka safar hai,\nTere saath hai khushi bhari raatein.",

    "Tere saath ki khushboo,\nDil ki hai baatein khuli,\nZindagi ka safar hai,\nTere pyaar se bhari.",

    "Chaand se baatein karun,\nTujhse hi pyaar karun,\nZindagi ke safar mein,\nTera saath na chhodun.",

    "Mausam hai khushnuma,\nTere pyaar ki dua,\nHar pal mein tu saath ho,\nMeri zindagi ka jahan.",

    "Dil ki khushboo teri,\nTere saath hai khushi,\nZindagi mein rang bharun,\nTere pyaar se hamesha bhari.",

    "Phoolon ki khushboo hai,\nTere bina sab suna,\nZindagi ki raahon mein,\nTu hai mera jahan.",

    "Tere saath chalte hain,\nKhushiyon ki baatein karte hain,\nDil se jo baatein karun,\nUsme sirf tu hai mera saath.",

    "Mausam ki khushboo,\nDil ki hai pyaas,\nTere saath ki khushi,\nMeri zindagi ka aas.",

    "Chand se pyaara sa,\nTera pyaar hai asmaan,\nTere bina adhura sa,\nMera pyaar ka safar hai yahan.",

    "Tere saath ki khushboo,\nMeri zindagi ka jahan,\nTere bina sab suna,\nTu hai mera pyaar ka samaan.",

    "Dil ki gehraiyon se,\nTere liye hai baatein,\nZindagi ki khushboo hai,\nTere saath ki khushiyaan yeh raatein.",

    "Phoolon ki tarah khilte,\nTere saath hai khushiyan,\nZindagi ki raahon mein,\nTere saath hai sab kuch hai pyaar ka armaan.",

    "Har khushi mein tera saath,\nHar dard mein hai tera pyaar,\nZindagi ka safar hai pyaara,\nTere bina sab suna sa hai yeh sansaar.",

    "Tere bina kuch nahi,\nDil mein teri yaad hai,\nZindagi ke har rang mein,\nTere saath mein hai mera jahan.",

    "Chandni raat ki khushboo,\nTere pyaar ka nasha,\nZindagi ki raahon mein,\nTere saath ki hai khushiyaan sada.",

    "Mausam ki khushboo hai,\nTere saath ki yaad hai,\nZindagi ka safar hai,\nTere bina sab suna sa hai yeh baat hai.",

    "Dil ki baatein teri,\nTere pyaar se bhari,\nZindagi ke rang hain,\nTere saath mein khushiyan bhari.",

    "Tere bina sab suna,\nDil mein teri yaad hai,\nZindagi ki har baat hai,\nMere pyaar ka armaan hai.",

    "Raat ki khamoshi,\nTere pyaar ki baatein,\nZindagi ki khushboo hai,\nTere bina sab suna hai yeh raatein.",

    "Phoolon ki khushboo hai,\nTere saath ka rang hai,\nZindagi mein tu hai,\nMeri khushiyon ka asmaan hai.",

    "Tere saath ki khushboo,\nMeri zindagi ka jahan,\nHar khushi mein tera saath,\nMera pyaar hai tera armaan.",

    "Dil se dil tak,\nTere pyaar ki baatein,\nZindagi ka safar hai,\nTere bina sab suna sa hai yeh raatein.",

    "Tere saath ki khushboo,\nDil ki hai baatein khuli,\nZindagi ka safar hai,\nTere pyaar se bhari khushiyan yeh raatein.",

    "Chand se pyaara sa,\nTere pyaar ka nasha,\nZindagi ka rang hai,\nMeri khushiyon ka hai tu saath.",

    "Mausam hai khushnuma,\nTere pyaar ki dua,\nHar pal mein tu saath ho,\nMeri zindagi ka jahan.",

    "Zindagi ke rang hain,\nTere saath ki khushiyan,\nHar dard ko bhulaaye,\nTu hai mera pyaar ka samaan.",

    "Phoolon ki tarah khilte,\nTere saath ki khushboo,\nZindagi ki raahon mein,\nTu hai mera pyaar ka jadoo.",

    "Tere bina adhura sa,\nMera yeh pyaar ka safar,\nTujhse hi hai khushi,\nHar din mera hai teri yaad.",

    "Har khushi ka raaz,\nTere saath hai khaas,\nZindagi ka safar hai,\nTu hai mera aasmaan.",

    "Chandni raaton ka jahan,\nTere pyaar ka armaan,\nTere bina sab suna,\nTu hai mera asmaan.",

    "Raat ki khamoshi,\nTere pyaar ki baatein,\nDil ki gehraiyon mein,\nHai sirf teri yaad.",

    "Tere pyaar ka nasha,\nHar pal mein hai jashn,\nZindagi ka hai rang,\nTu hai mera armaan.",

    "Tere saath ki khushboo,\nMeri zindagi ka jahan,\nTere bina sab suna,\nTu hai mera pyaar ka samaan.",

    "Dil ki khushboo teri,\nTere saath hai khushi,\nZindagi mein rang bharun,\nTere pyaar se hamesha bhari."
];

const generateShayariBtn = document.getElementById("generate-shayari-btn");
const shayariText = document.getElementById("shayari");

generateShayariBtn.addEventListener("click", () => {
    const randomIndex = Math.floor(Math.random() * shayariList.length);
    shayariText.innerHTML = shayariList[randomIndex].replace(/,/g, '<br>'); // Replace commas with line breaks

    // Add animation
    shayariText.style.opacity = "0"; // Fade out
    shayariText.style.transform = "translateY(20px)"; // Move down

    setTimeout(() => {
        shayariText.style.opacity = "1"; // Fade in
        shayariText.style.transform = "translateY(0)"; // Move to original position
    }, 300); // Delay to allow the fade out to complete
});

document.addEventListener("DOMContentLoaded", () => {
const quoteList = [
    "Love is the bridge between you and everything.",
    "Happiness blooms from within.",
    "In every tear, there is a lesson.",
    "Love is a canvas furnished by nature.",
    "Happiness is a journey, not a destination.",
    "Sadness is just a moment passing.",
    "Love knows no boundaries.",
    "Happiness is contagious; spread it.",
    "Every ending is a new beginning.",
    "Love is the heartbeat of the universe.",
    "Find joy in the little things.",
    "Sadness makes the heart grow fonder.",
    "In love, every day is a new adventure.",
    "Happiness is a choice you make.",
    "Sadness teaches us about appreciation.",
    "Love is the light in the dark.",
    "Happiness is found in the present.",
    "Every heartbreak is a lesson learned.",
    "Love is a promise kept.",
    "Joy is the simplest form of gratitude.",
    "Sadness is a fleeting visitor.",
    "In love, even silence speaks volumes.",
    "Happiness is the art of being content.",
    "Every sorrow has its purpose.",
    "Love is the soul's greatest treasure.",
    "Happiness is a warm hug.",
    "In sadness, we find our strength.",
    "Love is the poetry of the heart.",
    "Happiness dances in the heart.",
    "Every wound heals with time.",
    "Love is the song of the heart.",
    "True happiness lies in the little moments.",
    "Sadness is the shadow of joy.",
    "Love is the ultimate truth.",
    "Happiness is a fleeting moment.",
    "Sadness reveals the beauty of love.",
    "Love is a journey worth taking.",
    "Happiness is a state of mind.",
    "Every scar tells a story.",
    "In love, we find our purpose.",
    "Happiness is a warm cup of tea.",
    "Sadness is a reminder to cherish joy.",
    "Love is a gentle breeze.",
    "Happiness is a sunbeam in winter.",
    "Every cloud has a silver lining.",
    "Love is the essence of life.",
    "Happiness is a quiet heart.",
    "Sadness teaches us compassion.",
    "Love is the art of giving.",
    "Happiness is the light in the darkness.",
    "Every ending is a new beginning.",
    "Love is the most beautiful mistake.",
    "Happiness is a choice we make.",
    "In sadness, we discover our strength.",
    "Love is a journey, not a destination.",
    "Happiness is the key to success.",
    "Every tear has its reason.",
    "In love, we find our home.",
    "Happiness is a gentle smile.",
    "Sadness adds depth to joy.",
    "Love is the soul's language.",
    "Happiness is found in the present moment.",
    "Every moment is a gift.",
    "In love, we find ourselves.",
    "Happiness is a melody that resonates.",
    "Sadness is the flip side of joy.",
    "Love is the heartbeat of existence.",
    "Happiness is a state of being.",
    "Every sunrise is a new beginning.",
    "In love, we discover true freedom.",
    "Happiness is a warm embrace.",
    "Sadness brings wisdom.",
    "Love is the light that guides us.",
    "Happiness is the beauty of life.",
    "Every smile tells a story.",
    "In love, we become whole.",
    "Happiness is the joy of living.",
    "Sadness is a chapter, not the book.",
    "Love is the greatest adventure.",
    "Happiness is a heart full of gratitude.",
    "Every moment is a chance to shine.",
    "In love, we find our purpose.",
    "Happiness is a journey worth taking.",
    "Sadness is a temporary visitor.",
    "Love is the essence of humanity.",
    "Happiness is a treasure worth seeking.",
    "Every ending is a new beginning.",
    "In love, we discover the extraordinary.",
    "Happiness is the song of the soul.",
    "Sadness is the price of love.",
    "Love is the thread that binds us.",
    "Happiness is a warm blanket.",
    "Every heartbeat tells a story.",
    "In love, we find our strength.",
    "Happiness is the art of living.",
    "Sadness is a teacher in disguise.",
    "Love is a journey of discovery.",
    "Happiness is the sunshine of life.",
    "Every tear is a testament to love.",
    "In love, we find our light.",
    "Happiness is a gentle breeze.",
    "Sadness enriches our experience.",
    "Love is the dance of the heart.",
    "Happiness is a fleeting moment.",
    "Every sunset is a reminder of beauty.",
    "In love, we find our joy.",
    "Happiness is a warm cup of coffee.",
    "Sadness deepens our understanding.",
    "Love is a beautiful adventure.",
    "Happiness is the fragrance of life.",
    "Every moment is an opportunity.",
    "In love, we discover ourselves.",
    "Happiness is the light of hope.",
    "Sadness is a bridge to empathy.",
    "Love is the essence of being.",
    "Happiness is a gentle whisper.",
    "Every heartbeat is a gift.",
    "In love, we find our truth.",
    "Happiness is a journey, not a destination.",
    "Sadness is a reminder to cherish joy.",
    "Love is the heartbeat of existence.",
    "Happiness is the beauty of simplicity.",
    "Every tear tells a story.",
    "In love, we find our home.",
    "Happiness is a fleeting glance.",
    "Sadness adds depth to our experience.",
    "Love is the light that guides us.",
    "Happiness is a moment of peace.",
    "Every moment is precious.",
    "In love, we discover magic.",
    "Happiness is a warm smile.",
    "Sadness is a part of the journey.",
    "Love is the essence of joy.",
    "Happiness is the melody of life.",
    "Every day is a new chance.",
    "In love, we find our freedom.",
    "Happiness is the gift of gratitude.",
    "Sadness teaches us resilience.",
    "Love is the poetry of existence.",
    "Happiness is the essence of life.",
    "Every heartbeat is a celebration.",
    "In love, we discover our purpose.",
    "Happiness is a gentle caress.",
    "Sadness is a stepping stone.",
    "Love is the soul's journey.",
    "Happiness is a beautiful sunrise.",
    "Every moment is a blessing.",
    "In love, we find our strength.",
    "Happiness is a treasure to cherish.",
    "Sadness is a path to wisdom.",
    "Love is the greatest adventure.",
    "Happiness is the sunshine after rain.",
    "Every ending is a new beginning.",
    "In love, we find our truth.",
    "Happiness is a warm hug.",
    "Sadness is a part of life.",
    "Love is the magic of existence.",
    "Happiness is a choice we make.",
    "Every tear is a sign of love.",
    "In love, we find our joy.",
    "Happiness is a moment to cherish.",
    "Sadness is a teacher of empathy.",
    "Love is the heartbeat of the universe.",
    "Happiness is the beauty of now.",
    "Every heartbeat tells a story.",
    "In love, we discover ourselves.",
    "Happiness is a journey worth taking.",
    "Sadness is a chapter in life.",
    "Love is the essence of humanity.",
    "Happiness is a gentle breeze.",
    "Every moment is an opportunity to shine.",
    "In love, we find our light.",
    "Happiness is a treasure worth seeking.",
    "Sadness enriches our experience.",
    "Love is the dance of the heart.",
    "Happiness is the art of living.",
    "Every sunset is a reminder of beauty.",
    "In love, we find our joy.",
    "Happiness is a warm cup of tea.",
    "Sadness adds depth to joy.",
    "Love is a beautiful adventure.",
    "Happiness is the fragrance of life.",
    "Every moment is a chance to celebrate.",
    "In love, we discover the extraordinary.",
    "Happiness is the song of the soul.",
    "Sadness is a bridge to understanding.",
    "Love is the light in the darkness.",
    "Happiness is the heartbeat of life.",
    "Every tear has a purpose.",
    "In love, we find our truth.",
    "Happiness is a fleeting moment.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the essence of being.",
    "Happiness is a warm embrace.",
    "Every heartbeat tells a tale.",
    "In love, we find our peace.",
    "Happiness is a moment of clarity.",
    "Sadness teaches us to treasure joy.",
    "Love is the journey of the heart.",
    "Happiness is the light of hope.",
    "Every moment is a gift to cherish.",
    "In love, we find our strength.",
    "Happiness is a journey of discovery.",
    "Sadness is a reminder of love's depth.",
    "Love is the magic of existence.",
    "Happiness is the beauty of every day.",
    "Every heartbeat is a celebration of life.",
    "In love, we find our joy.",
    "Happiness is a gentle reminder.",
    "Sadness adds richness to our journey.",
    "Love is the song of the heart.",
    "Happiness is a warm light.",
    "Every moment is a chance for happiness.",
    "In love, we find our truth.",
    "Happiness is a treasure worth seeking.",
    "Sadness is a chapter in our story.",
    "Love is the essence of life.",
    "Happiness is a gentle touch.",
    "Every tear is a testament to love.",
    "In love, we find our freedom.",
    "Happiness is a warm feeling.",
    "Sadness is a part of the journey.",
    "Love is the heartbeat of the soul.",
    "Happiness is a beautiful memory.",
    "Every moment is a precious gift.",
    "In love, we discover our magic.",
    "Happiness is a gentle whisper.",
    "Sadness deepens our understanding.",
    "Love is the light that guides us.",
    "Happiness is a melody of joy.",
    "Every tear tells a story of hope.",
    "In love, we find our strength.",
    "Happiness is a moment of bliss.",
    "Sadness is a teacher of compassion.",
    "Love is the greatest adventure.",
    "Happiness is the essence of living.",
    "Every heartbeat is a reminder to love.",
    "In love, we find our home.",
    "Happiness is a gentle breeze.",
    "Sadness is a stepping stone to joy.",
    "Love is the dance of existence.",
    "Happiness is a treasure in our hearts.",
    "Every moment is a chance to create.",
    "In love, we discover true happiness.",
    "Happiness is a warm sunbeam.",
    "Sadness adds depth to our journey.",
    "Love is the poetry of life.",
    "Happiness is the art of being alive.",
    "Every tear is a sign of growth.",
    "In love, we find our joy.",
    "Happiness is a fleeting glance of beauty.",
    "Sadness is a reminder to cherish joy.",
    "Love is the light in the shadows.",
    "Happiness is a gentle caress of kindness.",
    "Every heartbeat is a celebration of love.",
    "In love, we find our purpose.",
    "Happiness is a treasure worth sharing.",
    "Sadness is a chapter that enriches the soul.",
    "Love is the essence of who we are.",
    "Happiness is a moment of clarity.",
    "Every moment is a gift to treasure.",
    "In love, we find our magic.",
    "Happiness is a warm embrace of friendship.",
    "Sadness teaches us to appreciate joy.",
    "Love is the melody of existence.",
    "Happiness is the light that guides us.",
    "Every heartbeat tells a story of hope.",
    "In love, we discover our true selves.",
    "Happiness is a journey worth taking.",
    "Sadness is a reminder of love's depth.",
    "Love is the greatest adventure of all.",
    "Happiness is a warm feeling inside.",
    "Every moment is a chance to shine.",
    "In love, we find our strength.",
    "Happiness is a treasure we hold dear.",
    "Sadness is a part of life’s tapestry.",
    "Love is the light that brightens our path.",
    "Happiness is the essence of every day.",
    "Every heartbeat is a celebration of existence.",
    "In love, we find our joy.",
    "Happiness is a gentle touch from the heart.",
    "Sadness adds depth to the journey.",
    "Love is the dance of the soul.",
    "Happiness is a beautiful memory to cherish.",
    "Every moment is a chance to create joy.",
    "In love, we discover true happiness.",
    "Happiness is a warm sunbeam on a cold day.",
    "Sadness is a reminder to appreciate life.",
    "Love is the song of the heart's journey.",
    "Happiness is the art of living fully.",
    "Every tear tells a story of resilience.",
    "In love, we find our peace.",
    "Happiness is a gentle reminder of beauty.",
    "Sadness deepens our appreciation for joy.",
    "Love is the greatest gift of all.",
    "Happiness is the light that shines within.",
    "Every heartbeat is a chance to love.",
    "In love, we find our true essence.",
    "Happiness is a treasure worth seeking.",
    "Sadness is a part of the human experience.",
    "Love is the heartbeat of life.",
    "Happiness is a warm embrace of kindness.",
    "Every moment is a chance to shine bright.",
    "In love, we discover our truth.",
    "Happiness is a gentle whisper of hope.",
    "Sadness teaches us the value of joy.",
    "Love is the melody of our existence.",
    "Happiness is the beauty of the present.",
    "Every tear is a sign of growth and healing.",
    "In love, we find our strength and courage.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness adds richness to our life’s tapestry.",
    "Love is the light that guides us home.",
    "Happiness is the essence of our being.",
    "Every heartbeat is a celebration of life.",
    "In love, we discover our deepest selves.",
    "Happiness is a warm cup of tea shared.",
    "Sadness is a reminder to cherish every joy.",
    "Love is the greatest adventure of the heart.",
    "Happiness is the art of embracing the moment.",
    "Every sunset is a promise of a new dawn.",
    "In love, we find our ultimate freedom.",
    "Happiness is a gentle caress from the universe.",
    "Sadness enriches our understanding of joy.",
    "Love is the dance of the cosmos.",
    "Happiness is a treasure we hold close.",
    "Every moment is a gift to be cherished.",
    "In love, we find our true magic.",
    "Happiness is a warm light in the darkness.",
    "Sadness is a chapter in our beautiful story.",
    "Love is the heartbeat of the universe.",
    "Happiness is the light that guides our way.",
    "Every tear is a testament to our journey.",
    "In love, we discover our greatest strength.",
    "Happiness is a fleeting moment of peace.",
    "Sadness is a reminder to appreciate every joy.",
    "Love is the essence of our existence.",
    "Happiness is a gentle reminder to cherish life.",
    "Every heartbeat tells a story of love.",
    "In love, we find our home and belonging.",
    "Happiness is a treasure worth celebrating.",
    "Sadness is a part of the human experience.",
    "Love is the greatest adventure of all.",
    "Happiness is the beauty of every heartbeat.",
    "Every moment is a chance to create joy.",
    "In love, we find our truth and purpose.",
    "Happiness is a warm embrace from the heart.",
    "Sadness teaches us to treasure the joy.",
    "Love is the light that brightens our journey.",
    "Happiness is a melody of the soul.",
    "Every tear tells a story of resilience.",
    "In love, we discover true happiness.",
    "Happiness is a gentle caress of kindness.",
    "Sadness adds depth to our experiences.",
    "Love is the dance of existence.",
    "Happiness is a beautiful memory to hold.",
    "Every moment is a chance to shine.",
    "In love, we find our strength and joy.",
    "Happiness is a treasure worth holding onto.",
    "Sadness is a chapter that enriches our lives.",
    "Love is the heartbeat of the cosmos.",
    "Happiness is the essence of every day.",
    "Every heartbeat is a reminder of life.",
    "In love, we find our joy and peace.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness is a teacher of appreciation.",
    "Love is the light in the shadows.",
    "Happiness is a gentle touch of warmth.",
    "Every moment is an opportunity to create.",
    "In love, we discover our magic.",
    "Happiness is a warm sunbeam on a cold day.",
    "Sadness teaches us to cherish every joy.",
    "Love is the song of our hearts.",
    "Happiness is the art of living fully.",
    "Every tear tells a story of growth.",
    "In love, we find our strength and purpose.",
    "Happiness is a gentle reminder of beauty.",
    "Sadness adds depth to our journey.",
    "Love is the essence of our being.",
    "Happiness is the melody of life.",
    "Every heartbeat is a celebration of existence.",
    "In love, we discover our truth.",
    "Happiness is a treasure worth seeking.",
    "Sadness is a part of our journey.",
    "Love is the light that guides us.",
    "Happiness is a warm embrace of kindness.",
    "Every moment is a chance to shine bright.",
    "In love, we find our joy.",
    "Happiness is a gentle caress of hope.",
    "Sadness teaches us to appreciate joy.",
    "Love is the greatest adventure of all.",
    "Happiness is the beauty of the present.",
    "Every tear is a sign of resilience.",
    "In love, we find our home.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness adds richness to our life’s story.",
    "Love is the dance of the heart.",
    "Happiness is a treasure we hold dear.",
    "Every moment is an opportunity to create joy.",
    "In love, we discover our true selves.",
    "Happiness is a warm feeling inside.",
    "Sadness is a reminder to cherish every joy.",
    "Love is the heartbeat of the universe.",
    "Happiness is a gentle touch from the heart.",
    "Every heartbeat tells a story of hope.",
    "In love, we find our truth and purpose.",
    "Happiness is a warm embrace from the soul.",
    "Sadness is a chapter in our beautiful journey.",
    "Love is the greatest gift of all.",
    "Happiness is the light that shines within.",
    "Every tear tells a story of love.",
    "In love, we find our strength.",
    "Happiness is a moment of peace.",
    "Sadness teaches us the value of joy.",
    "Love is the melody of existence.",
    "Happiness is the beauty of every day.",
    "Every heartbeat is a celebration of life.",
    "In love, we discover our joy.",
    "Happiness is a gentle reminder of beauty.",
    "Sadness adds depth to our experiences.",
    "Love is the light that guides us home.",
    "Happiness is the essence of living fully.",
    "Every moment is a chance to treasure.",
    "In love, we find our true magic.",
    "Happiness is a warm cup of coffee shared.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the dance of the soul.",
    "Happiness is a beautiful memory to cherish.",
    "Every moment is a chance to create.",
    "In love, we discover true happiness.",
    "Happiness is a gentle caress of kindness.",
    "Sadness deepens our understanding of joy.",
    "Love is the heartbeat of life.",
    "Happiness is a warm embrace from the heart.",
    "Every heartbeat tells a story of love.",
    "In love, we find our truth.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness is a teacher of compassion.",
    "Love is the greatest adventure.",
    "Happiness is the light that guides us.",
    "Every moment is a gift to cherish.",
    "In love, we discover our true selves.",
    "Happiness is a warm feeling of belonging.",
    "Sadness is a part of the journey.",
    "Love is the essence of who we are.",
    "Happiness is a treasure worth celebrating.",
    "Every heartbeat is a reminder of joy.",
    "In love, we find our strength and courage.",
    "Happiness is a gentle reminder of hope.",
    "Sadness adds depth to our journey.",
    "Love is the melody of existence.",
    "Happiness is the beauty of the present.",
    "Every moment is a chance to shine bright.",
    "In love, we discover our magic.",
    "Happiness is a warm embrace of kindness.",
    "Sadness is a reminder to treasure joy.",
    "Love is the dance of our hearts.",
    "Happiness is a beautiful memory to hold.",
    "Every heartbeat is a celebration of life.",
    "In love, we find our joy and peace.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness teaches us to appreciate every joy.",
    "Love is the light in the shadows.",
    "Happiness is a gentle caress of warmth.",
    "Every moment is an opportunity to create.",
    "In love, we find our truth.",
    "Happiness is a treasure worth seeking.",
    "Sadness is a chapter in our story.",
    "Love is the heartbeat of the universe.",
    "Happiness is the essence of living fully.",
    "Every heartbeat tells a story of love.",
    "In love, we find our strength.",
    "Happiness is a warm feeling inside.",
    "Sadness is a reminder to cherish joy.",
    "Love is the magic of existence.",
    "Happiness is a melody of the soul.",
    "Every tear tells a story of resilience.",
    "In love, we discover true happiness.",
    "Happiness is a gentle touch from the heart.",
    "Sadness deepens our understanding of joy.",
    "Love is the dance of life.",
    "Happiness is a beautiful memory to cherish.",
    "Every moment is a chance to shine.",
    "In love, we find our true selves.",
    "Happiness is a warm embrace of kindness.",
    "Sadness is a reminder of the joy.",
    "Love is the heartbeat of existence.",
    "Happiness is a gentle reminder of beauty.",
    "Every heartbeat is a celebration of joy.",
    "In love, we find our strength and purpose.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness teaches us to cherish every joy.",
    "Love is the light that guides our path.",
    "Happiness is a treasure worth holding.",
    "Every moment is a gift to be treasured.",
    "In love, we discover true joy.",
    "Happiness is a warm cup of coffee shared.",
    "Sadness is a chapter in our beautiful story.",
    "Love is the greatest adventure of all.",
    "Happiness is the art of living fully.",
    "Every heartbeat is a reminder to love.",
    "In love, we find our home.",
    "Happiness is a gentle touch of kindness.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the dance of existence.",
    "Happiness is a beautiful memory to hold.",
    "Every moment is a chance to create joy.",
    "In love, we find our strength.",
    "Happiness is a warm embrace from the heart.",
    "Sadness adds depth to our journey.",
    "Love is the heartbeat of the universe.",
    "Happiness is a gentle reminder of beauty.",
    "Every heartbeat tells a story of resilience.",
    "In love, we discover our truth.",
    "Happiness is a fleeting moment of peace.",
    "Sadness is a part of our journey.",
    "Love is the light that guides us.",
    "Happiness is a warm embrace of kindness.",
    "Every moment is an opportunity to shine.",
    "In love, we find our joy.",
    "Happiness is a gentle reminder of hope.",
    "Sadness teaches us to treasure joy.",
    "Love is the greatest gift of all.",
    "Happiness is the essence of our existence.",
    "Every tear tells a story of growth.",
    "In love, we find our strength and courage.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness is a teacher of empathy.",
    "Love is the heartbeat of life.",
    "Happiness is a warm feeling inside.",
    "Every moment is a chance to celebrate.",
    "In love, we find our true selves.",
    "Happiness is a treasure worth seeking.",
    "Sadness adds richness to our journey.",
    "Love is the light that brightens our path.",
    "Happiness is a gentle touch of warmth.",
    "Every heartbeat is a celebration of existence.",
    "In love, we discover our magic.",
    "Happiness is a warm sunbeam on a cold day.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the song of our hearts.",
    "Happiness is the art of living fully.",
    "Every tear tells a story of resilience.",
    "In love, we find our peace.",
    "Happiness is a moment of joy.",
    "Sadness teaches us the value of love.",
    "Love is the greatest adventure of all.",
    "Happiness is a beautiful memory to cherish.",
    "Every moment is a chance to shine.",
    "In love, we find our joy and purpose.",
    "Happiness is a warm embrace from the heart.",
    "Sadness adds depth to our experiences.",
    "Love is the heartbeat of the universe.",
    "Happiness is the essence of living.",
    "Every heartbeat tells a story of love.",
    "In love, we discover our truth.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness is a reminder to treasure joy.",
    "Love is the light in the shadows.",
    "Happiness is a gentle caress of kindness.",
    "Every moment is an opportunity to create.",
    "In love, we find our strength.",
    "Happiness is a treasure worth holding.",
    "Sadness is a part of the journey.",
    "Love is the magic of existence.",
    "Happiness is a beautiful memory to cherish.",
    "Every heartbeat is a celebration of life.",
    "In love, we discover our true selves.",
    "Happiness is a warm feeling of belonging.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the dance of our hearts.",
    "Happiness is the essence of our being.",
    "Every moment is a chance to create joy.",
    "In love, we find our strength.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness deepens our understanding of love.",
    "Love is the light that guides our way.",
    "Happiness is a gentle reminder of beauty.",
    "Every heartbeat tells a story of hope.",
    "In love, we discover true happiness.",
    "Happiness is a warm embrace from the soul.",
    "Sadness teaches us to treasure every joy.",
    "Love is the heartbeat of life.",
    "Happiness is a beautiful melody.",
    "Every moment is a chance to shine.",
    "In love, we find our joy.",
    "Happiness is a treasure worth celebrating.",
    "Sadness is a chapter in our beautiful journey.",
    "Love is the greatest adventure of all.",
    "Happiness is the art of living fully.",
    "Every heartbeat is a reminder to love.",
    "In love, we find our truth and purpose.",
    "Happiness is a warm embrace from the heart.",
    "Sadness adds depth to our experiences.",
    "Love is the light that guides us.",
    "Happiness is a gentle touch of warmth.",
    "Every moment is an opportunity to create.",
    "In love, we discover our magic.",
    "Happiness is a fleeting moment of peace.",
    "Sadness is a reminder to cherish every joy.",
    "Love is the melody of existence.",
    "Happiness is a gentle reminder of beauty.",
    "Every heartbeat is a celebration of joy.",
    "In love, we find our strength and courage.",
    "Happiness is a warm cup of tea shared.",
    "Sadness deepens our appreciation for joy.",
    "Love is the dance of life.",
    "Happiness is a beautiful memory to hold.",
    "Every moment is a chance to shine bright.",
    "In love, we discover our true selves.",
    "Happiness is a gentle caress of kindness.",
    "Sadness teaches us the value of joy.",
    "Love is the greatest gift of all.",
    "Happiness is the light that shines within.",
    "Every heartbeat tells a story of love.",
    "In love, we find our joy and peace.",
    "Happiness is a warm feeling of belonging.",
    "Sadness is a part of the human experience.",
    "Love is the heartbeat of the universe.",
    "Happiness is a gentle reminder to cherish life.",
    "Every tear tells a story of growth.",
    "In love, we find our home.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness adds richness to our journey.",
    "Love is the dance of existence.",
    "Happiness is the essence of living fully.",
    "Every heartbeat is a celebration of life.",
    "In love, we discover our true selves.",
    "Happiness is a warm embrace of kindness.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the light that brightens our path.",
    "Happiness is a treasure worth seeking.",
    "Every moment is a chance to create joy.",
    "In love, we find our strength and courage.",
    "Happiness is a beautiful memory to cherish.",
    "Sadness deepens our understanding of love.",
    "Love is the melody of existence.",
    "Happiness is a gentle touch from the heart.",
    "Every heartbeat tells a story of hope.",
    "In love, we find our joy.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness teaches us to treasure every joy.",
    "Love is the heartbeat of life.",
    "Happiness is the beauty of every day.",
    "Every moment is an opportunity to shine.",
    "In love, we discover our truth.",
    "Happiness is a warm embrace from the soul.",
    "Sadness is a reminder to cherish every joy.",
    "Love is the dance of our hearts.",
    "Happiness is the essence of our being.",
    "Every heartbeat tells a story of love.",
    "In love, we find our strength.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness deepens our understanding of joy.",
    "Love is the greatest adventure of all.",
    "Happiness is a gentle reminder of beauty.",
    "Every moment is a chance to create joy.",
    "In love, we find our magic.",
    "Happiness is a warm sunbeam on a cold day.",
    "Sadness is a teacher of appreciation.",
    "Love is the heartbeat of existence.",
    "Happiness is a beautiful melody.",
    "Every heartbeat is a reminder to love.",
    "In love, we find our joy.",
    "Happiness is a treasure worth holding.",
    "Sadness adds depth to our experiences.",
    "Love is the light that guides our way.",
    "Happiness is a gentle reminder of beauty.",
    "Every moment is a chance to shine bright.",
    "In love, we discover our true selves.",
    "Happiness is a warm embrace of kindness.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the magic of existence.",
    "Happiness is the light that shines within.",
    "Every heartbeat tells a story of love.",
    "In love, we find our strength.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness teaches us to treasure joy.",
    "Love is the essence of our being.",
    "Happiness is a gentle touch of warmth.",
    "Every moment is an opportunity to create joy.",
    "In love, we discover our magic.",
    "Happiness is a warm sunbeam on a cold day.",
    "Sadness deepens our understanding of love.",
    "Love is the greatest gift of all.",
    "Happiness is a gentle reminder of hope.",
    "Every heartbeat is a celebration of existence.",
    "In love, we find our joy.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness is a part of the journey.",
    "Love is the light that guides us.",
    "Happiness is a warm embrace from the heart.",
    "Every moment is a chance to create joy.",
    "In love, we discover our strength and courage.",
    "Happiness is a beautiful memory to cherish.",
    "Sadness adds richness to our journey.",
    "Love is the dance of existence.",
    "Happiness is the essence of living fully.",
    "Every heartbeat tells a story of love.",
    "In love, we find our true selves.",
    "Happiness is a warm feeling inside.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the melody of our existence.",
    "Happiness is a gentle touch of kindness.",
    "Every moment is a chance to shine bright.",
    "In love, we discover our truth.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness teaches us to treasure every joy.",
    "Love is the heartbeat of life.",
    "Happiness is the beauty of every heartbeat.",
    "Every moment is an opportunity to celebrate.",
    "In love, we find our joy and peace.",
    "Happiness is a warm embrace from the heart.",
    "Sadness is a teacher of appreciation.",
    "Love is the greatest adventure of all.",
    "Happiness is a beautiful memory to hold.",
    "Every heartbeat is a reminder of life.",
    "In love, we discover our strength.",
    "Happiness is a gentle reminder of beauty.",
    "Sadness adds depth to our experiences.",
    "Love is the light that guides our way.",
    "Happiness is the essence of our being.",
    "Every moment is a chance to create joy.",
    "In love, we find our truth.",
    "Happiness is a warm embrace of kindness.",
    "Sadness is a reminder to cherish joy.",
    "Love is the magic of existence.",
    "Happiness is a fleeting moment of clarity.",
    "Every heartbeat is a celebration of existence.",
    "In love, we discover our joy.",
    "Happiness is a warm sunbeam on a cold day.",
    "Sadness deepens our appreciation for love.",
    "Love is the greatest gift of all.",
    "Happiness is a gentle reminder of hope.",
    "Every moment is a chance to shine.",
    "In love, we find our strength.",
    "Happiness is a beautiful memory to cherish.",
    "Sadness adds richness to our journey.",
    "Love is the heartbeat of the universe.",
    "Happiness is a gentle caress from the heart.",
    "Every heartbeat tells a story of resilience.",
    "In love, we discover our truth.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness teaches us to treasure every joy.",
    "Love is the light that guides us.",
    "Happiness is the beauty of every heartbeat.",
    "Every moment is an opportunity to celebrate.",
    "In love, we find our joy and peace.",
    "Happiness is a warm embrace from the soul.",
    "Sadness is a teacher of empathy.",
    "Love is the dance of our hearts.",
    "Happiness is a treasure worth seeking.",
    "Every heartbeat is a reminder of love.",
    "In love, we discover our true selves.",
    "Happiness is a warm feeling inside.",
    "Sadness is a reminder to appreciate joy.",
    "Love is the melody of existence.",
    "Happiness is a gentle touch of kindness.",
    "Every moment is a chance to shine bright.",
    "In love, we discover our strength.",
    "Happiness is a beautiful memory to hold.",
    "Sadness adds depth to our experiences.",
    "Love is the heartbeat of life.",
    "Happiness is the essence of our being.",
    "Every moment is a chance to create joy.",
    "In love, we find our truth.",
    "Happiness is a fleeting moment of clarity.",
    "Sadness is a reminder to treasure every joy.",
    "Love is the magic of existence.",
    "Happiness is a warm embrace from the heart.",
    "Every heartbeat tells a story of resilience.",
    "In love, we discover true happiness.",
    "Happiness is a gentle reminder of beauty.",
    "Sadness teaches us the value of joy.",
    "Love is the greatest adventure of all.",
    "Happiness is the beauty of every day.",
    "Every moment is an opportunity to celebrate.",
    "In love, we find our joy.",
    "Happiness is a warm feeling of belonging.",
    "Sadness is a chapter in our journey.",
    "Love is the heartbeat of the universe.",
    "Happiness is a gentle touch of warmth.",
    "Every heartbeat is a reminder to love.",
    "In love, we discover our magic.",
    "Happiness is a fleeting moment of bliss.",
    "Sadness deepens our understanding of love.",
    "Love is the light that guides us."

];


    const generateQuoteBtn = document.getElementById("generate-quote-btn");
    const quoteText = document.getElementById("quote");

    generateQuoteBtn.addEventListener("click", () => {
        const randomIndex = Math.floor(Math.random() * quoteList.length);
        quoteText.innerHTML = quoteList[randomIndex].replace(); // Replace commas with line breaks

        // Add animation
        quoteText.style.opacity = "0"; // Fade out
        quoteText.style.transform = "translateY(20px)"; // Move down

        setTimeout(() => {
            quoteText.style.opacity = "1"; // Fade in
            quoteText.style.transform = "translateY(0)"; // Move to original position
        }, 300); // Delay to allow the fade out to complete
    });
});

const menuBar = document.getElementById('menu-bar');
const navLinks = document.getElementById('nav-links');

menuBar.addEventListener('click', () => {
    navLinks.classList.toggle('show'); // Toggle 'show' class to display nav links
});

// Submission
document.getElementById('postForm').addEventListener('submit', function(event) {
    event.preventDefault(); // Prevent default form submission

    // Gather form data
    const name = document.getElementById('name').value;
    const country = document.getElementById('country').value;
    const choice = document.getElementById('choice').value;
    const content = document.getElementById('content').value;

    // Create the payload
    const payload = {
        username: "Post Submission",
        avatar_url: "", // Optional: URL for an avatar
        embeds: [{
            title: choice === "shayari" ? "New Shayari" : "New Quote",
            description: content,
            fields: [
                {
                    name: "Submitted By",
                    value: name,
                    inline: true
                },
                {
                    name: "Country",
                    value: country,
                    inline: true
                }
            ]
        }]
    };

    // Send data to Discord webhook
    fetch('https://discordapp.com/api/webhooks/1287570745135730788/_8UN2Of0CIpYRoBb022gskMcj7k-jv_kX647YQph1AewXvFsMze3Ffgs9V1YarU4QOpl', { // Replace with your Discord webhook URL
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
    })
    .then(response => {
        if (response.ok) {
            alert('Post submitted successfully!');
            document.getElementById('postForm').reset(); // Reset form after submission
        } else {
            alert('Failed to submit post.');
        }
    })
    .catch(error => {
        console.error('Error:', error);
        alert('Error submitting post.');
    });
});



